# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mondrian/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),mondrian)

$(call add-radio-file-sha1-checked,radio/abl.img,18f665adc10de75e4d8f8322200b16067872b70a)
$(call add-radio-file-sha1-checked,radio/aop.img,76d2b29ee82952550cc712d12b5562225c64e0c5)
$(call add-radio-file-sha1-checked,radio/aop_config.img,356de9bf1211da254b290cb48ccd779adc706b31)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,0718c6238e61900365de510643ff152c0288bae3)
$(call add-radio-file-sha1-checked,radio/cpucp.img,c669e0bc21a9b53494e06663f4b915113d0448a7)
$(call add-radio-file-sha1-checked,radio/devcfg.img,3533c27dceff7aa98a97446293aec71c035fc60b)
$(call add-radio-file-sha1-checked,radio/dsp.img,259329c9822fa19d5ba7f6e06794c44ceec3d220)
$(call add-radio-file-sha1-checked,radio/featenabler.img,bb071d67032eb6c976163c8c89c7891d5b6012c9)
$(call add-radio-file-sha1-checked,radio/hyp.img,942fd76dd01fb71e6820ee41ec510455c17405eb)
$(call add-radio-file-sha1-checked,radio/imagefv.img,ac91a19c8b311e75e8bf54ebaceea0e9a0d95a9f)
$(call add-radio-file-sha1-checked,radio/keymaster.img,6911b68780f602c39cced17a1f169bc1ab92f98c)
$(call add-radio-file-sha1-checked,radio/modem.img,a4da4919f3a50d96f38026b12d9a3a24b9f1d280)
$(call add-radio-file-sha1-checked,radio/qupfw.img,3930963b53aefdbf306225ab099985baf195e5f0)
$(call add-radio-file-sha1-checked,radio/shrm.img,f5700314f1589041ac32f1e9b5abe4e35f23e2d6)
$(call add-radio-file-sha1-checked,radio/tz.img,daa4c7634e3f35d32794134aac00f6695dee5747)
$(call add-radio-file-sha1-checked,radio/uefi.img,2977cf542081e044110af671fc8cae63246cf576)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,d30508f3cc3fdbb8be9127be5030ab35bc502bae)
$(call add-radio-file-sha1-checked,radio/vm-bootsys.img,ba20165ced28dca887728c18dedd4135ad492976)
$(call add-radio-file-sha1-checked,radio/xbl.img,a7178d43f5f97bab57ccdc7288b0784cb7a039f5)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,108be8af33398ced449346e55453b4046066dc75)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,2d0df3c43696c031e18053a9e77b26d917363b94)

endif
