# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mondrian/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),mondrian)

$(call add-radio-file-sha1-checked,radio/abl.img,b805f41636b4dd6584d71c6ea72b061dabc095e6)
$(call add-radio-file-sha1-checked,radio/aop.img,7a57b1f988afbb78c64bdcc9454337fc1ef3efaf)
$(call add-radio-file-sha1-checked,radio/aop_config.img,c677e6ec0b3d54a1518ecdde74af810e8845b092)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,7486e6866408f6d156b670be5e59fff776419c1c)
$(call add-radio-file-sha1-checked,radio/cpucp.img,0bf5cfaf1397ee4ea2d5654a78caa5c65c98282a)
$(call add-radio-file-sha1-checked,radio/devcfg.img,842a1f2f328c307724273a313b885bb84fed5a36)
$(call add-radio-file-sha1-checked,radio/dsp.img,259329c9822fa19d5ba7f6e06794c44ceec3d220)
$(call add-radio-file-sha1-checked,radio/featenabler.img,010a90a7092d6eed5003ceef19e3d439ea1b400d)
$(call add-radio-file-sha1-checked,radio/hyp.img,1b789a6c29fcc7f9c0845b483240b85487906dbd)
$(call add-radio-file-sha1-checked,radio/imagefv.img,f49f40c5d152298909305ff0535bce0634a5ff7f)
$(call add-radio-file-sha1-checked,radio/keymaster.img,0eda202c434176f50ee693de7d2dfe5b18bddb3a)
$(call add-radio-file-sha1-checked,radio/modem.img,d90c5dc600216e4b847adaaa167804646c93bd3c)
$(call add-radio-file-sha1-checked,radio/qupfw.img,2f2f145b73304852aaf617da380d89a3d97a2812)
$(call add-radio-file-sha1-checked,radio/shrm.img,4c1fd4130c44608b588cdc52e07464db30a675ac)
$(call add-radio-file-sha1-checked,radio/tz.img,2923127a5e7b6e3b93bf439d94d0c5b6c49d06a1)
$(call add-radio-file-sha1-checked,radio/uefi.img,171b8798f34f2f514d1e654ba2a53b3d03df348d)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,480c7cf98935eae186d8e30ca31b9005adaf0230)
$(call add-radio-file-sha1-checked,radio/vm-bootsys.img,ba20165ced28dca887728c18dedd4135ad492976)
$(call add-radio-file-sha1-checked,radio/xbl.img,ce4a074e9e49c3eec1e35858f4172b4a75d2a61b)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,f3cd95e5c8450168458a71ebb145c41b3021340e)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,7c85db34e49db028c0a50592c8d8a404629de50e)

endif
