# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mondrian/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),mondrian)

$(call add-radio-file-sha1-checked,radio/abl.img,e66502f3b7aa300533dec3ba1052c37ea361648e)
$(call add-radio-file-sha1-checked,radio/aop.img,00b4bbeb6ae5c3a51791753622be80da6dc5986f)
$(call add-radio-file-sha1-checked,radio/aop_config.img,ae9a2c38fea7059e478f0993e4e2001101292034)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,0f14eb60268c050b0ac134a22a27ce2783fa373d)
$(call add-radio-file-sha1-checked,radio/cpucp.img,7c0167fdbf1f35de8631d2b0a5670a0f8bf41297)
$(call add-radio-file-sha1-checked,radio/devcfg.img,a7333fff3db0f97ce66754347241703a1e7a3304)
$(call add-radio-file-sha1-checked,radio/dsp.img,259329c9822fa19d5ba7f6e06794c44ceec3d220)
$(call add-radio-file-sha1-checked,radio/featenabler.img,3af81da0d431ee1816cdd9caaee4137e6c69547f)
$(call add-radio-file-sha1-checked,radio/hyp.img,3facdbee5a8a87695394949a725a2898ed49d33d)
$(call add-radio-file-sha1-checked,radio/imagefv.img,b2ccbc4e4f54b54d95ab554aceafb53afbe8fd93)
$(call add-radio-file-sha1-checked,radio/keymaster.img,fdcbc4dcb4529f90be7fd91b46388eaf6fedd75e)
$(call add-radio-file-sha1-checked,radio/modem.img,be746e8d9aa75e15af13d45dcb0fcc568299e7b5)
$(call add-radio-file-sha1-checked,radio/qupfw.img,93db322888528c314b44b3beb1ab951359123969)
$(call add-radio-file-sha1-checked,radio/shrm.img,35a8f6993b23b5253e1e75ed30e374781af25a6d)
$(call add-radio-file-sha1-checked,radio/tz.img,8a8737e7a08d45dd1adc5c898d9b0f4e0d1ebc44)
$(call add-radio-file-sha1-checked,radio/uefi.img,78e3b42952788e833718c1f5bdacfeadf496d754)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,ed3c8b3936bfa2f0404483548c0b1dd469ddade4)
$(call add-radio-file-sha1-checked,radio/vm-bootsys.img,ba20165ced28dca887728c18dedd4135ad492976)
$(call add-radio-file-sha1-checked,radio/xbl.img,cdeee63ec330294117232a5e384e5496dc1fb9af)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,2150484aca0876618f031e3987144e4ac6cce067)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,f4e89511a84de78913fde1fbe23c8ea898b6b56e)

endif
